### ISSUE TITLE
Build is failing on jruby-head

### ISSUE THREAD

**Issue by KL-7** [twitter/twitter-cldr-rb#124]
JRuby-head builds were failing for a while now ([first failed build](https://travis-ci.org/twitter/twitter-cldr-rb/builds/30679612)). It might be related to [this JRuby issue](https://github.com/jruby/jruby/issues/985).

**Comment by camertron** [comment]
At the moment it looks like JRuby 9000 builds are failing because of a YAML parsing issue. I tried to dig into it, but didn't get very far.

**Comment by camertron** [comment]
JRuby builds are passing now.
