### ISSUE TITLE
Adopt new Travis CI infrastructure

### ISSUE THREAD

**Issue by caniszczyk** [twitter/twitter-cldr-rb#146]
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by caniszczyk** [comment]
We probably should look at if we need to build on all these old rubies...

Also, we need to find a way to not use 'sudo'

**Comment by caniszczyk** [comment]
cc: @KL-7

**Comment by caniszczyk** [comment]
How can I use it?
Using our new container-based stack only requires one additional line in your .travis.yml:

sudo: false

What are the restrictions?
Using sudo isn't possible (right now)

Our new container stack uses Docker under the hood. This has a lot of benefits like fast boot times and better utilization of available machine resources. But it also comes with restrictions imposed by security.

At this point, it's not possible to use any command requiring sudo in your builds.

If you require sudo, for instance to install Ubuntu packages, a workaround is to use precompiled binaries, uploading them to S3 and downloading them as part of your build, installing them into a non-root directory.

**Comment by caniszczyk** [comment]
I see we need one thing to install: libonig-dev via apt-get

**Comment by caniszczyk** [comment]
@KL-7 any idea why we need 'libonig-dev' or @camertron ?

**Comment by KL-7** [comment]
Looks like it's all [about 1.8](https://github.com/twitter/twitter-cldr-rb/commit/a1f9a42e3c6178112b8ab288be3fca879b1932f9).

**Comment by caniszczyk** [comment]
omg lets drop it :)

**Comment by KL-7** [comment]
I can look into it tomorrow and try to remove everything 1.8-related from the code. Then we can drop it from the build and release a new 1.8-free version.

**Comment by caniszczyk** [comment]
Ok, I'm going to drop a build w/o 1.8 with the new Travis CI infra to see how fast the builds can improve

**Comment by KL-7** [comment]
ok :crying_cat_face:

**Comment by caniszczyk** [comment]
TIME TO SEE!  :dash: https://travis-ci.org/twitter/twitter-cldr-rb/builds/46388433

**Comment by camertron** [comment]
Just a gentle reminder to please bump the major version when releasing a 1.8-free version :)

**Comment by KL-7** [comment]
Yeah, definitely.

**Comment by camertron** [comment]
I believe this has been resolved - we appear to be using the new Travis containerized infrastructure.
