### ISSUE TITLE
Switch to i18napis.appspot.com for postal codes.

### ISSUE THREAD

**Issue by archSeer** [twitter/twitter-cldr-rb#166]
CLDR v27 deprecated the postal code file: http://unicode.org/reports/tr35/tr35-info.html#Postal_Code_Validation

**Comment by camertron** [comment]
Awesome, thanks for the heads-up @archSeer. It shouldn't be too difficult to switch to the new source. I'll see what I can do.

**Comment by camertron** [comment]
See #167
