### ISSUE TITLE
Unicode Properties Refactor

### ISSUE THREAD

**Issue by camertron** [twitter/twitter-cldr-rb#170]
The Unicode Character Database (UCD) contains a full list of all the characters currently supported by the Unicode standard. This database also contains large lists of _properties_ for these characters. Properties are like categories in that groups of characters belong to a single property. Properties have _names_, but can also have one or more property _values_. Properties can therefore be thought of as name/value pairs, where each pair (as opposed to just the name) is unique. For instance, the "Math" property contains all mathematical characters (eg. `+`, `=`, etc). "Math" is a good example of a property that doesn't have any property values. "General_Category" on the other hand contains a number of property values. For example, all uppercase letters, regardless of script, have the General_Category property name and the "Lu" property value.

Up until now, twitter-cldr-rb has only had limited support for Unicode properties. I've been working on refactoring our current properties system, and have come up with the following set of pull requests:

- [x] Update blocks: https://github.com/twitter/twitter-cldr-rb/pull/169
- [x] FileSystemTrie https://github.com/twitter/twitter-cldr-rb/pull/171
- [x] RangeSet improvements: #172 
- [x] Import Unicode properties: #173 
- [x] Property trie dumps: #175
- [x] Properties refactor: #176
- [x] Cleanup: #177

**Comment by KL-7** [comment]
That's a lot of pull requests, @camertron. Great work! :+1: 
I'm not that familiar with Unicode properties, so I guess I'll need to check some docs before reviewing all the code, but I'll take a look at all this in the next few days.

**Comment by camertron** [comment]
@KL-7 Yeah it's quite a few PRs :) Thanks in advance for looking at them. I could have submitted the whole thing as one giant PR, but that didn't seem very nice. So now you've got 7, hehehe.

Again, thanks in advance. Here's some [documentation](http://unicode.org/reports/tr44/#Properties).

**Comment by KL-7** [comment]
Sorry it took me forever to get to this, Cameron. I'm slowly going through the PRs and plan to finish this in the afternoon.

**Comment by KL-7** [comment]
Alright, all done. It still turned out to be more code than I could thoroughly dive into right now, so I did a semi-quick review, adding a few minor comments here and there. I don't want you to be blocked on me for much longer, so I trust you tested everything and made sure it matches the spec :shipit:

**Comment by camertron** [comment]
Ok, thanks for taking a look @KL-7. I have tested the feature pretty thoroughly via unit tests and also by hand as I was writing it. I'll address your comments and merge :)
