### ISSUE TITLE
Shorter territory localization code?

### ISSUE THREAD

**Issue by Anthony-Gaudino** [twitter/twitter-cldr-rb#181]
To localize a territory one can use `TwitterCldr::Shared::Territories::from_territory_code_for_locale("gb", :pt)` for example to translate U.K. to Portuguese.

I would like to know if this is the best way to do this, I didn't find any documentation on the readme.md file.

I tough there would be a short alternative like `:gb.localize(:pt)` or `:gb.localize(:pt).to_territory`.

**Comment by camertron** [comment]
Hey @Anthony-Gaudino, thanks for putting this on my radar. There should definitely be some documentation for this feature, and it should be easier to use as you suggested. As far as the latter concern goes, we should be able to make it easier to use by adding a method to [`LocalizedSymbol`](https://github.com/twitter/twitter-cldr-rb/blob/master/lib/twitter_cldr/localized/localized_symbol.rb). Do you have time to submit a PR?

**Comment by Anthony-Gaudino** [comment]
Sure, I already have it working like this `:gb.localize(:pt).as_territory`, if `as_territory` is not a good name, please let me know.

I will also update the documentation and tests accordingly.

**Comment by camertron** [comment]
`#as_territory` is perfect :)
