### ISSUE TITLE
English currencies don't always go on the left

### ISSUE THREAD

**Issue by ptarjan** [twitter/twitter-cldr-rb#185]
How can I make `localize` understand that in English we put the cent marker on the right?

```
[1] pry(main)> 30.localize.to_currency.to_s(currency: '¢', precision: 0)
=> "¢30"
```

but I want `30¢`

**Comment by camertron** [comment]
Hey @ptarjan, from what I can tell the CLDR data set does not contain a format for cents, even in the most recent version. I think the closest you're going to be able to get is the decimal form, eg. $0.30. Unfortunately we can only be as accurate as the data :)

**Comment by ptarjan** [comment]
@camertron thanks for the reply. I guess I'll have to hack around it on my end. :(
