### ISSUE TITLE
Native casefolding Unicode in Ruby 2.4

### ISSUE THREAD

**Issue by Nakilon** [twitter/twitter-cldr-rb#190]
Does this Ruby 2.4.0pre feature https://bugs.ruby-lang.org/issues/10085 mean I don't need twitter-cldr-rb anymore if I used it only for casefolding?

**Comment by camertron** [comment]
Yes I believe that is correct. You shouldn't need Twitter-cldr-rb once case folding is released in Ruby itself. Nice find, I didn't know about this!

**Comment by Nakilon** [comment]
It's from https://www.ruby-lang.org/en/news/2016/06/20/ruby-2-4-0-preview1-released/
