### ISSUE TITLE
Add tibetan language (bo)

### ISSUE THREAD

**Issue by groe** [twitter/twitter-cldr-rb#198]
I have tried adding support für tibetan (`bo`) to twitter-cldr by adding the directory in `resources/locales` and running the `rake update` task with both ruby and jruby (as suggested by @camertron in #186) but I could not get it to work :disappointed: 

Some of the rake (sub) tasks failed with errors and I could not figure out the exact reasons (seemed like API incompatibilities, too many parameters, nil objects and alike), so I tried to run them individually. Eventually I managed to get `TwitterCldr.supported_locale?(:bo)` to return `true` but my collation test case (sorting a tibetan string array) failed. I was probably missing something here...

Could you have a look at it and maybe add support for the `bo` locale?

(My attempts are committed here, but I wouldn't rely on it: https://github.com/groe/twitter-cldr-rb)

**Comment by camertron** [comment]
@groe ah sorry about that 😢  I wish adding locales was easier. I'll see what I can do about adding Tibetan.

**Comment by groe** [comment]
@camertron No worries. That would be perfect, thank you!

**Comment by groe** [comment]
Any news, @camertron? I've noticed there is a `bo` branch in github already?

**Comment by camertron** [comment]
Yes, I was able this past week to make locale importing easier (see the [README](https://github.com/twitter/twitter-cldr-rb#adding-new-locales)). [Here's a PR](https://github.com/twitter/twitter-cldr-rb/pull/199) for Tibetan, how does it look?
