### ISSUE TITLE
Date formatting is incorrect for en_GB

### ISSUE THREAD

**Issue by natemueller** [twitter/twitter-cldr-rb#201]
It looks like eee886e5 reversed month/date order for en_GB.  We noticed that yMd switched from "dd/MM/y" to "M/d/y" and it looks like other date formats changed as well.

**Comment by camertron** [comment]
Hey @natemueller, it looks like the date formats for en_GB (as well as the base language en) were changed in CLDR v29 which is the dataset used by twitter-cldr-rb v4.0. Unfortunately there's not much you or I can do in the short term to fix the data. I would however encourage you to [file a ticket](http://unicode.org/cldr/trac/newticket) against the CLDR project. You can also email their mailing list at cldr-users@unicode.org.

As a workaround, you should be able to use the old format manually. I will admit it's a little cumbersome:

```ruby
data_reader = TwitterCldr::DataReaders::DateTimeDataReader.new(:en_GB)
tokens = data_reader.tokenizer.full_tokenize('dd/MM/y')
result = data_reader.formatter.format(tokens, DateTime.now)
```

**Comment by natemueller** [comment]
Can you explain?  From my reading of the XML it looks like dd/MM/y is still correct.  main/en_GB.xml doesn't specify a yMd format.  According to supplemental/supplementalData.xml it inherits from en_001.xml, which defines yMd as dd/MM/r.

**Comment by natemueller** [comment]
A little more research.  It looks like in CLDR 23 en_GB had a default inheritance and explicitly defined yMd.  In CLDR 24 it switched to inherit from en_001.  In CLDR 27 the yMd definition moved up to en_001.  The ruby library doesn't handle this because ruby-cldr uses I18n::Locale::Fallbacks instead of the parentLocales section in supplementalData.xml when merging files.

Is that accurate?  I'm happy to submit a patch (to this and ruby-cldr) but I want to make sure I'm not barking up the wrong tree.

**Comment by camertron** [comment]
Ahh ok, I just learned something new. I actually had no idea parentLocales existed. I would welcome a PR or two against ruby-cldr and twitter-cldr-rb. Thanks for researching :)

**Comment by camertron** [comment]
Parent locales are respected and implemented in later versions of the library, so I'll close this issue.
