### ISSUE TITLE
Not working for the Canada 3 digits postal code

### ISSUE THREAD

**Issue by GopalChavan** [twitter/twitter-cldr-rb#214]
I am using this gem in my application to validate the postal codes
like this
postal_code = TwitterCldr::Shared::PostalCodes.for_territory('ca')
errors.add(:zipcode, :invalid) if !postal_code.valid?('T2P') # false

but this is not working for the postal code of Canada with 3 alphabets

**Comment by camertron** [comment]
Hey @GopalChavan, forgive my ignorance, but aren't Canadian postal codes always 6 letters long? From the [Wikipedia article](https://en.wikipedia.org/wiki/Postal_codes_in_Canada):

> A Canadian postal code is a six-character string that forms part of a postal address in Canada. Like British, Irish and Dutch postcodes, Canada's postal codes are alphanumeric. They are in the format A1A 1A1, where A is a letter and 1 is a digit, with a space separating the third and fourth characters.

I tried to search for `T2P` on [Canada Post's website](https://www.canadapost.ca/cpo/mc/personal/postalcode/fpc.jsf) without any luck. What am I missing here?

**Comment by camertron** [comment]
Hey @GopalChavan, if you click on any of those three-letter postal codes that come up in the Google search, you'll see that they correspond to an entire region or neighborhood, not a specific home or business.

What's your use-case? Are you validating partial postal codes or whole neighborhoods?

**Comment by GopalChavan** [comment]
In our application its the shipping address of the customer

**Comment by camertron** [comment]
Ok, so your Canadian customers are actually entering 3-digit postal codes?

**Comment by GopalChavan** [comment]
As of now, the application is not in production, just we are testing the Canadian postal codes. What would be the valid postal code for Canada? Is that 6 digits only or it may 3 digits.

**Comment by camertron** [comment]
I believe all Canadian postal codes are supposed to be six digits, or more specifically, three digits, a space, then another three digits. For example, this is the address for one of the Bank of Montréal branches:

630, boulevard René-Lévesque Ouest, Montreal, QC H3B 1S6

Notice the H3B 1S6 postal code.
