### ISSUE TITLE
FR: short_decimal and currency combination formatter.

### ISSUE THREAD

**Issue by jaymes-stripe** [twitter/twitter-cldr-rb#216]
I'm working on a request to display `ja` as both a `short_decimal` and a `currency` type at the same time. (not 5億/`short_decimal` or ¥500,000,000/`currency`, but ¥5億)

Is there a way to have a formatter that would deal with both?

I'm happy to start putting together a PR, but would need some help, and it looks like this is a slow-moving repo. Let me know if this is feasible or not.

**Comment by camertron** [comment]
Hey @jaymes-stripe,

I'm still (semi-actively) maintaining this repo and happy to review any PRs :)

All the formatting logic is derived from CLDR data. I'm not sure if there are specific rules per locale, but it should be feasible to do what you're asking by refactoring and then composing the existing data readers, tokenizers, and formatters. I don't think it's possible to do this with the current object model.

**Comment by jaymes-stripe** [comment]
@camertron Thanks! I'll see if I have some time in the next few weeks to take a closer look at this and get something fleshed o ut.

**Comment by camertron** [comment]
Closing for now.
