### ISSUE TITLE
CLDR 35 Dev Branch

### ISSUE THREAD

**Issue by bherila** [twitter/twitter-cldr-rb#225]
@camertron  do you have a dev branch you could share for the cldr v35?  Anything I can do to help?

Thanks,
Ben

**Comment by camertron** [comment]
Hey @bherila, apologies for taking so long to respond. Yes, I have a dev branch going, [`cldr35`](https://github.com/twitter/twitter-cldr-rb/tree/cldr35). I also added the additional locales you requested. I've been hacking away at it for the last week or so but there are still a few mysterious test failures. If you've got some extra time I would welcome your help fixing them :) I'd focus on the rule based number format (RBNF) failures.

**Comment by bherila** [comment]
Thanks @camertron , I will have a look and if I manage to fix any of them will send a PR to that branch.
