### ISSUE TITLE
Incorrect list formatter behaviour 

### ISSUE THREAD

**Issue by valodzka** [twitter/twitter-cldr-rb#233]
TwitterCldr::Formatters::ListFormatter.new(:zh).format(['a', 'b', 'c'], :'unit-narrow')

Expected result: "abc"
Actual result: "c"

**Comment by valodzka** [comment]
Obvious fix would be replace:

https://github.com/twitter/twitter-cldr-rb/blob/master/lib/twitter_cldr/formatters/list_formatter.rb#L57 

with          ` result.gsub!(/(\d)/) { elements[$1.to_i] }`

**Comment by camertron** [comment]
Hey @valodzka thanks for the bug report! This should be fixed in v6.0.1 :)
