### ISSUE TITLE
Incorrect LikelySubtags.locale_for behaviour

### ISSUE THREAD

**Issue by valodzka** [twitter/twitter-cldr-rb#235]
Based on this http://unicode.org/reports/tr35/#Likely_Subtags I expect that:

    und_Arab_AF ⇒ fa_Arab_AF
    OR
    und_CH ⇒ de_Latn_CH

But actual result is different:

    und_Arab_AF ⇒ af_Arab_ZA
    und_CH ⇒ ch_Latn_GA

**Comment by camertron** [comment]
Hey @valodzka, thanks for the bug report. Looks like regions are getting mis-identified as languages, eg. AF (Afghanistan) is identified as af (Afrikaans), and CH (Switzerland) is identified as ch (Chamorro).

Should be fixed in v6.0.2.
