### ISSUE TITLE
Month names :narrow format returns array of digits rather than the first letter of each month

### ISSUE THREAD

**Issue by jesselasalle** [twitter/twitter-cldr-rb#248]
**Describe the bug**
`TwitterCldr::Shared::Calendar.new(:en).months(:narrow)` used to return:

[
    [ 0] "J",
    [ 1] "F",
    [ 2] "M",
    [ 3] "A",
    [ 4] "M",
    [ 5] "J",
    [ 6] "J",
    [ 7] "A",
    [ 8] "S",
    [ 9] "O",
    [10] "N",
    [11] "D"
]

Now returns:

[
    [ 0] "1",
    [ 1] "2",
    [ 2] "3",
    [ 3] "4",
    [ 4] "5",
    [ 5] "6",
    [ 6] "7",
    [ 7] "8",
    [ 8] "9",
    [ 9] "10",
    [10] "11",
    [11] "12"
]

**To Reproduce**
1. Load 6.4.0 in irb
2. Run `TwitterCldr::Shared::Calendar.new(:en).months(:narrow)` 
3. Note the output
4. Load 6.11.0 in irb
5. Run `TwitterCldr::Shared::Calendar.new(:en).months(:narrow)` 
6. Compare the output

**Expected behavior**
The method should return:

[
    [ 0] "J",
    [ 1] "F",
    [ 2] "M",
    [ 3] "A",
    [ 4] "M",
    [ 5] "J",
    [ 6] "J",
    [ 7] "A",
    [ 8] "S",
    [ 9] "O",
    [10] "N",
    [11] "D"
]

**Screenshots**

**Environment**
Rails 4.2.11.3, Ruby 2.4.0

**Additional context**

**Comment by jesselasalle** [comment]
Made this PR after a quick analysis: https://github.com/twitter/twitter-cldr-rb/pull/249

**Comment by camertron** [comment]
Hey @jesselasalle, thanks for bringing this problem to my attention. It turns out a number of other locales were also impacted. I just published v6.11.1 with the fix, please let me know if things are still looking wonky :)

**Comment by jesselasalle** [comment]
Can't test right now, but thanks a ton for addressing this quickly. I'll follow up!

**Comment by DRBragg** [comment]
@camertron Sorry for the delay on this. I confirmed all is good with this on 6.11.1
