### ISSUE TITLE
Remove lone release

### ISSUE THREAD

**Issue by sandstrom** [twitter/twitter-cldr-rb#255]
Since the Github releases isn't used (which is totally fine!), how about removing the lone release?

https://github.com/twitter/twitter-cldr-rb/releases

Upon a cursory look, it may seem like this project hasn't had any any releases since 2014, which is obviously incorrect.

**Comment by camertron** [comment]
Hah yeah that's a good idea. We had grand plans to use releases but it never really happened 😏 

I just deleted the release, thanks!
