### ISSUE TITLE
Add support for yMMMMd (October 7, 2022)

### ISSUE THREAD

**Issue by aytekin-stripe** [twitter/twitter-cldr-rb#258]
**Is your feature request related to a problem? Please describe.**
We have a use case to print dates such as "October 7, 2022". We would like support for this format.

**Describe the solution you'd like**
Please include this in supported formats.

**Comment by camertron** [comment]
Hey @aytekin-stripe, I believe you want the "long" format option, eg:

```ruby
Date.today.localize(:en).to_long_s
```

This is one of the standard date formats and will produce "October 17, 2022".

**Comment by aytekin-stripe** [comment]
Thanks @camertron this works great! 👍
