### ISSUE TITLE
Wrong language name is returned for Norwegian Nynorsk (nn)

### ISSUE THREAD

**Issue by c960657** [twitter/twitter-cldr-rb#263]
**Describe the bug**
Wrong language name is returned for Norwegian Nynorsk (`nn`). This is not a supported locale, but it should still be possible to retrieve the language name.

**To Reproduce**
```ruby
TwitterCldr::Shared::Languages.from_code_for_locale(:nn, :en)
# Expected: Norwegian Nynorsk
# Actual: Norwegian Bokmål
```

**Comment by camertron** [comment]
Hey @c960657, thanks for the bug report! TwitterCLDR for some reason was converting the locale to one the library supports before looking it up in the mapping data, meaning it converted `:nn` to `:nb` before performing the lookup. I fixed the bug and published v6.11.5.
