### ISSUE TITLE
Unicode, ICU, CLDR update

### ISSUE THREAD

**Issue by noraj** [twitter/twitter-cldr-rb#266]
Those are the actual version of the data: 

https://github.com/twitter/twitter-cldr-rb/blob/afb5c20aa8eeb23926e78865bf205541974a7dd1/lib/twitter_cldr/versions.rb#L8-L10

Would it be possible to update to:

- Unicode 15.0.0
- ICU 74.0.1
- CLDR 43

**Comment by camertron** [comment]
Thanks for asking about this. I'm in the process of updating the lib now. Got ~4 test failures left.

**Comment by noraj** [comment]
Hey there

- Unicode 16 is available since 10 September 2024 https://www.unicode.org/versions/Unicode16.0.0/
- ICU 76 since 24 October 2024 that supports Unicode 16.0 https://unicode-org.github.io/icu/download/76.html
- CLDR 46 and 46.1 https://cldr.unicode.org/downloads/cldr-46

https://github.com/twitter/twitter-cldr-rb/blob/29758ac8ae284cd98becee90dd698bf1fa0e252f/lib/twitter_cldr/versions.rb#L7-L10

**Comment by camertron** [comment]
Hey @noraj, twitter_cldr v6.13.0 was published a few days ago with support for CLDR v46.1 and Unicode v16. In the future, please file a separate issue for requests like this 😄
